# Generated by Django 4.2.16 on 2024-11-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_ddiet_post_diet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
